### ISSUE TITLE
accessing discovery url failed: connection refused

### ISSUE THREAD

**Issue by aabou** [jerneyio/kong-keycloak-mobile-demo#1]
Hello @jerneyio,

first, thanks for this initiative, but i tried to flow your tuto, but I encountered a problem at the time of the discovery.
when i try to access http://localhost:8000/api-docs/ or http://localhost:8000/ i have this message:
`accessing discovery url (http://localhost:8180/auth/realms/kong/.well-known/openid-configuration) failed: connection refused`

but when i try http://localhost:8180/auth/realms/kong/.well-known/openid-configuration
I get the the true json response: --> I can access to my json discovery!
[
![image](https://user-images.githubusercontent.com/24956777/49808921-ecb6f800-fd5d-11e8-8e21-296fa72c2a36.png)
](url)

my keycloack client:
![capture](https://user-images.githubusercontent.com/24956777/49808318-8ed5e080-fd5c-11e8-8581-0fac08e29293.PNG)

my kong plugin:
`{
  "created_at": 1544535818000,
  "config": {
    "response_type": "code",
    "realm": "kong",
    "redirect_after_logout_uri": "/",
    "scope": "openid",
    "token_endpoint_auth_method": "client_secret_post",
    "logout_path": "/logout",
    "client_id": "kong",
    "bearer_only": "no",
    "ssl_verify": "no",
    "discovery": "http://localhost:8180/auth/realms/kong/.well-known/openid-configuration",
    "client_secret": "63f323a1-d8ff-48af-bedc-123253107fda"
  },
  "id": "088ed153-21dd-4b3e-a338-e8168bc9df09",
  "name": "oidc",
  "enabled": true
}`

Do you have any idea?

thank you in advance.

**Comment by jerneyio** [comment]
A call from `localhost` from the container will never exit the container. `localhost` refers to whatever host or container you're running in. Kong is trying to find the discovery document from `localhost` i.e., itself, where it doesn't exist. Please see the tutorial I've added to the README.md where I mention this issue.

**Comment by aabou** [comment]
Thanks @jerneyio, I rectified the pull by making the correct IP (of my keycloak container). but can't access to my redirect uri, the redirection go in timeout.
net keycloack container conf:
`"Networks": {
    "kong-keycloak_keycloak-net": {
        "IPAMConfig": null,
        "Links": null,
        "Aliases": [
            "1cfc8b75f76e",
            "keycloak"
        ],
		....
        "Gateway": "172.19.0.1",
        "IPAddress": "172.19.0.3",
        ....
    }
}
`
From kong container, i can ping Gateway IP and i can get my json discovery, but can't do this action with IPAddress --> my discovery go on timeout!!!

I must do something in container (kong : docker file/ docker compose "environment") to have access to IPAdress of keycloack?

**Comment by jerneyio** [comment]
I have no idea what issue you're facing or how it relates to the tutorial I've posted. I make absolutely no reference to a "Gateway" or "Gateway IP". If you've followed the directions in my tutorial step-by-step and are having issues, you can let me know in the comments section of the post. But from what I can tell, the issue you're having is in no way related to this repository.

**Comment by aabou** [comment]
Thank you @jerneyio  for these valuable answers. i followed your tuto step by step. I think it's a docker issue be cause my kong can't access to keycloak network.

**Comment by jerneyio** [comment]
If it can't find the discovery URL, it *could* be that. But if it's timing out on the redirect uri, it could be something else. try disabling the OIDC plugin and see if you can connect to that redirect uri using Kong as a proxy.

**Comment by aabou** [comment]
I tried kong as a proxy with oidc "off" and i had this kong error:

> Kong Error
> An invalid response was received from the upstream server.

any idea!!

For information, this cmd is missing in your tuto:
`$ docker-compose up -d keycloak`
